# Generated by Django 2.2.17 on 2020-12-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Name', models.CharField(max_length=50)),
                ('Visitor_Vehicle_Number', models.CharField(max_length=50)),
                ('Visiting_Resident_Name', models.CharField(max_length=50)),
                ('Visitor_Contact_Number', models.CharField(max_length=10)),
                ('Vehicle_Owner_Name', models.CharField(max_length=50)),
                ('Vehicle_Type', models.CharField(max_length=50)),
            ],
        ),
    ]
