# Generated by Django 3.1.4 on 2020-12-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
